- hosts: masters[0]
  become: yes
  tasks:
    - name: Initialize kubeadm
      command: kubeadm init --pod-network-cidr=192.168.0.0/16

    - name: Set up kubeconfig
      shell: |
        mkdir -p /root/.kube
        cp /etc/kubernetes/admin.conf /root/.kube/config

    - name: Generate join command
      command: kubeadm token create --print-join-command
      register: join_cmd
      delegate_to: localhost
      run_once: true

    - name: Save join command
      set_fact:
        join_command: "{{ join_cmd.stdout }}"

