- name: Setup proxy VM for Ansible control
  hosts: proxy
  become: true
  gather_facts: false

  tasks:
    - name: Ensure .ssh directory exists
      file:
        path: /home/ubuntu/.ssh
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0700'

    - name: Check if private SSH key exists locally
      stat:
        path: "{{ lookup('env', 'HOME') }}/.ssh/user-key"
      delegate_to: localhost
      register: key_stat
      failed_when: not key_stat.stat.exists
      changed_when: false

    - name: Copy private SSH key to proxy
      copy:
        src: "{{ lookup('env', 'HOME') }}/.ssh/user-key"
        dest: /home/ubuntu/.ssh/id_rsa
        mode: '0600'
        owner: ubuntu
        group: ubuntu
      delegate_to: localhost
      when: key_stat.stat.exists

    - name: Copy ansible directory to proxy
      synchronize:
        src: "{{ playbook_dir }}/../"
        dest: "/home/ubuntu/ansible/"
        rsync_opts:
          - "--chmod=Du=rwx,Dg=rx,Do=rx,Fu=rw,Fg=r,Fo=r"
      delegate_to: localhost

    - name: Copy scripts directory to proxy
      synchronize:
        src: "{{ playbook_dir }}/../../scripts/"
        dest: "/home/ubuntu/scripts/"
        rsync_opts:
          - "--chmod=Du=rwx,Dg=rx,Do=rx,Fu=rw,Fg=r,Fo=r"
      delegate_to: localhost

    - name: Ensure script is executable
      file:
        path: "/home/ubuntu/scripts/run-cluster.sh"
        mode: '0755'
        owner: ubuntu
        group: ubuntu

    - name: Run the specified script on proxy
      shell: "/home/ubuntu/scripts/run-cluster.sh"
      args:
        chdir: "/home/ubuntu"
      register: run_result

    - name: Print script output
      debug:
        var: run_result.stdout
